### ISSUE TITLE
DisableFilters enables when writting in GlobalFilter input

### ISSUE THREAD

**Issue by jozef-rzadkosz** [TanStack/react-table#2787]
**Describe the bug (required)**
I found a bug with GlobalFilter implementation. When you type something in GlobalFilter input and e.g. FirstName column has disabled property: {disableFilters: true} the property 'canFilter' is set to true, when GlobalFilter input is empty this property becomes on false.

**Provide an example via Codesandbox! (required)**
Your link to reproduce is not working so I paste mine
https://codesandbox.io/s/bitter-fog-s59i4

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/bitter-fog-s59i4
2. Click on GlobalFilter "Search: 10000 records"
3. Type something
4. See that FirstName filter input is being shown (It shouldn't be)
5. Clear GlobalFilter input
6. See that FirstName input is now not visible

**Expected behavior (Recommended)**
When I want to disable filter on some columns It must be hidden. I found that canFilter property evaluates to true when you type something in GlobalFilter, maybe that will help you.

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.3
- Browser: Google Chrome
- Version: 86.0.4240.111

**Comment by dufourc** [comment]
Hey @freestyle09,

I've faced the same error. And you're right, it's because canFilter is set to true for every columns with disableGlobalFilter to false(default to false). To be accurate, everything happens at this line: https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useGlobalFilter.js#L116. _canFilter_ is set in every columns to know to which columns to apply the global filter.

I don't know if this is intended and if the canFilter is used somewhere else after that code.

I see several solutions:

- 1) Use another variable for that, like canGlobalFilter 
- 2) If this canFilter value is needed somewhere else, make the change immutable by creating a new array in a map.
- 3) If not, move the condition inside the filter to get filterableColumns here: https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useGlobalFilter.js#L123. Something like this:

```
 const filterableColumns = allColumns.filter(column =>
      getFirstDefined(
          column.disableGlobalFilter === true ? false : undefined,
          disableGlobalFilter === true ? false : undefined,
          true
        )
    )
```

What do think about the suggestions? I'm happy to make a PR, I just don't how this impact the rest of the code or why this has been done like this.

**Comment by freestyle09** [comment]
Yeah actually there's no such a big problem I am just writting in issues that anyone else can save time to solve this problem :) 
I have fixed that using another flag and it works perfect.

`return !column.disableFilters ? <div key={i}>{column.render('Filter')}</div> : null;`

Thanks for an answer ! :)

**Comment by dufourc** [comment]
Of course, thanks for opening it, I just faced the error this morning so it was a good timing. And thanks for the workaround, it works well apart than I'm not sure we are supposed to use this value (not in the typescript definition of the ColumnInstance) but this will do the trick for now 😃

Awaiting for an answer form the tanner or another maintainer to guide me more if we can put a fix for that.

**Comment by tannerlinsley** [comment]
This issue is either:
- Outdated
- Stale
- Fixed in v8
- Unable to be fixed in v7 without breaking changes and is slated for v8

If you feel this is incorrect, please reopen a new issue with a codesandbox reproduction or more info regarding the issue.
