### ISSUE TITLE
preFilteredRows stale with initialState.filters

### ISSUE THREAD

**Issue by maxsalven** [TanStack/react-table#2797]
**Describe the bug (required)**
If you provide initial state (text) filters with some text value, and then clear a filter, and then type again, the second filter receives **all** rows as `preFilteredRows`

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/dreamy-banzai-5xmgz?file=/src/App.js

**Steps To Reproduce (required)**

1. Delete the 'a' character in the First Name filter
2. Type an 'a' character in the First Name filter

**Expected behavior (Recommended)**
I expect the filter in Last Name to say "Search ~43000 records" (the exact number will vary between use as the data is randomly generated) but it says "Search 100000 records"

**Screenshots**
<img width="363" alt="Screen Shot 2020-10-24 at 9 57 44 AM" src="https://user-images.githubusercontent.com/4144910/97065379-6f0dd580-15df-11eb-8928-5330aa56577e.png">

You can see at the bottom of the screenshot, there are 43445 rows that match the current filter, but the Last Name filter component is receiving all 100,000 rows as `preFilteredRows`

**Comment by tannerlinsley** [comment]
With v8 on the horizon, we're cleaning up the repo to keep the momentum going strong. We have detected that this issue is either:
- Outdated
- Stale
- Unable to be fixed in v7 without breaking changes which are either already completed in v8 or slated for a subsequent v8 release

If you feel this is incorrect, please reopen a new issue with a codesandbox reproduction or more info regarding the issue.
