### ISSUE TITLE
Development bundle is inside production bundle

### ISSUE THREAD

**Issue by tomolenet** [TanStack/react-table#2926]
**Describe the bug (required)**
I use `react-table` in my project and use [rollup](https://rollupjs.org/) to bundle my project. But for some reason the `production` bundle of my project includes the `145 KB` size `react-table.development.js` bundle.

**Provide an example via Codesandbox! (required)**
Since its a [rollup](https://rollupjs.org/)-build issue its not possible.

**Steps To Reproduce (required)**

1. Create a project that use `react-table`.
2. Use `rollup` to bundle the project.
3. Inspect the output bundle.

**Expected behavior (Recommended)**
No `development` bundle in `production` build.

**Screenshots**
 Here is a screenshot of the `rollup-visualizer-plugin`. You can see that there is the `react-table.development.js` bundle inside.
![image](https://user-images.githubusercontent.com/38924650/102383930-65e02a00-3fcc-11eb-843c-239ccbba4b02.png)

**Additional context**
Not sure if it is a `react-table` specific issue? Is there any change to remove the `development`-bundle from the `production` output-bundle?

`rollup.config.js`
```js
import babel from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import external from 'rollup-plugin-peer-deps-external';
import inlineSvg from 'rollup-plugin-inline-svg';
import del from 'rollup-plugin-delete';
import visualizer from 'rollup-plugin-visualizer';
import filesize from 'rollup-plugin-filesize';
import pkg from './package.json';
import { terser } from 'rollup-plugin-terser';

export default {
  input: pkg.source,
  output: [
    { file: pkg.main, format: 'cjs' },
    { file: pkg.module, format: 'esm' }
  ],
  plugins: [
    del({ targets: ['dist/*'] }),
    resolve({
      extensions: ['.js', '.jsx']
    }),
    commonjs(),
    babel({
      babelHelpers: 'external',
      exclude: 'node_modules/**'
    }),
    inlineSvg(),
    external(),
    terser(),
    filesize(),
    visualizer()
  ],
  external: Object.keys(pkg.peerDependencies || {})
};
```
`package.json`
```json
  "scripts": {
    "build": "NODE_ENV=production rollup -c --environment INCLUDE_DEPS,BUILD:production"
  },
  ```

**Comment by datner** [comment]
please refine the issue down to just rollup (with as few plugins and modifications as possilbe)  and react-table, I can't tell what the culprit is, it could be bad input, bad output, del, resolve, commonjs, babel, inlineSvg, external, terser, or INCLUDE_DEPS.
though when it comes to bundling, I am very much inclined to think it's related to the bundler more than react-table. 
If you can't supply a code sandbox, a repo would be nice to have, I can't investigate otherwise

**Comment by tomolenet** [comment]
I did a small example at: https://github.com/tomolenet/rollup-bundle-react-table-example

For some reason without `resolve` and `commonjs` there is no build of `react-table` included.

You can check the `stats` files inside the repository.

**Comment by datner** [comment]
I'll take a look and try to diagnose if it's related to the bundler or the library

**Comment by locona** [comment]
If you make the following changes, react-table.development.js will no longer be included and the "bundle size" will be smaller.

node_modules/react-table/index.js
```
module.exports = require('./dist/react-table.production.min.js’)
```

Is there any other solution than this?

**Comment by dagerikhl** [comment]
I've also come across this problem. I suspect it's because the react-table index.js checks the runtime variable `process.env.NODE_ENV` to conclude which bundle to include, and Rollup (or rollup-plugin-commonjs) isn't able to discern which bundle should be included at build time and therefore includes both.

I thought It'd post here as I managed to find a solution that didn't require me to change the source files of react-table in node_modules:

1. Change all imports of react-table from `"react-table"` to `"react-table/dist/react-table.production.min"`.
2. If you're using Rollup with rollup-plugin-commonjs, add this entry to your commonjs config:
    ```
    commonjs({
      namedExports: {
        "react-table/dist/react-table.production.min": [
          "useFilters",
          "usePagination",
          "useRowSelect",
          "useRowState",
          "useSortBy",
          "useTable", // Or any other exports you're using
        ],
      }
    }),
    ```

_Note: This solution may have some impact on your development env, as you're now importing the production build in dev as well, and debugging may become somewhat harder in some cases because of the minification._

As for the issue at heart, I'm not sure how it can be resolved. I'm not sure it's possible for Rollup to use runtime variables to discard bundles, as it can't _know_ which one is the one actually used and therefore can't discard the other one. So I'm not much help there, unfortunately.
