### ISSUE TITLE
Sorting indicators does not update when using React.memo

### ISSUE THREAD

**Issue by nimabrownlee** [TanStack/react-table#2948]
**Describe the bug (required)**
When React.memo is used to render the columns/headers, the sorting booleans, does not trigger a re-render. 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/quizzical-feynman-f2y8l?file=/pages/index.js

**Steps To Reproduce (required)**
Try to sort using the codesandbox above. 

**Expected behavior (Recommended)**
It should trigger a re-render.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 87+

**Additional context**
Use the code that is commented out to see a working version.

**Comment by datner** [comment]
`React.memo` uses [shallowEquals](https://github.com/facebook/react/blob/v16.8.6/packages/shared/shallowEqual.js) unless told otherwise and is supposed to stop rerenders, this is working as intended

**Comment by datner** [comment]
also unrelated to `react-table`

**Comment by nimabrownlee** [comment]
@datner Hey, sure. Whats the fix then? I am forced to use `memo` to stop huge amount of re-renders.

**Comment by datner** [comment]
Try to change the diff function, for more in-depth help ask on stack overflow or something, sorry

**Comment by anglis** [comment]
Found a workaround. First of all even though you would use table instance state it would not be useful, because it is mutated as well. So in stateReducer I added a setter for component state. It gives me immutable state which I can use in memo equality callback.

For more explanation here is codesandbox: https://codesandbox.io/s/eloquent-dream-516xnl?file=/src/App.js

**Comment by dantman** [comment]
The same thing happens when trying to use memo to speed up rendering of table rows.

React Table's row selection breaks when a table row is memoized.

https://codesandbox.io/s/eloquent-dream-516xnl?file=/src/App.js

This is a major performance issue. If I remove `memo()` the onScroll re-renders in my app go from 22-28ms to 80-120ms. The scroll re-renders in question being triggered by TanStack's own react-virtual.

React Table should **not** be re-using and mutating the row object when it when it has changed, and assuming that table components are not memoized for performance. This is [fundamental to react](https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data), if this is intended behaviour then react-table is wrong. Beyond performance I understand there's also the possibility that examples like [Sub Components (Lazy)](https://react-table.tanstack.com/docs/examples/sub-components-lazy) and others that use extra components could encounter tearing in concurrent mode due to `row` being mutated during render.

It feels quite absurd that the [React Table docs](https://react-table.tanstack.com/docs/quick-start) say:
> It's important that we're using [React.useMemo](https://reactjs.org/docs/hooks-reference.html#usememo) here to ensure that our data isn't recreated on every render. If we didn't use React.useMemo, the table would think it was receiving new data on every render and attempt to recalculate a lot of logic every single time. Not cool!

Yet when it comes to memoizing table elements. React Table's intended behaviour that you cannot optimize element rendering for the exact same reason.

**Comment by alxHenry** [comment]
Also ran into this for column sort headers not updating when the components are memoized. Even after the sort state changes, the header groups are the same reference, even though they now include modified sort state.

For my case I ended up generating a key from the sort state and passing it to the memoized component. This feels pretty hacky though and I'm a little disappointed maintainers don't think this is a bug.
