### ISSUE TITLE
Filter not working for Custom Component

### ISSUE THREAD

**Issue by saifkamaal** [TanStack/react-table#2955]
Hello,

I am using the library and am able to display the table, however when i filter some columns which are based on custom components the filter does not work.

Ex:

```
{
        Header: 'Contact Phone',
        accessor: (value) =>  <PrimaryContact telephone={value.contactDetails.telephone} />,
        filter: 'fuzzyText',
      },
```

**Comment by datner** [comment]
accessor yields the "calculated" value and is filltered by it. As in, you're filtering out of a list of react components, and not accessors.

```ts
{
  Header: 'Contact Phone',
  accessor: 'contactDetails.telephone',
  filter: 'fuzzyText',
  Cell: ({value}) => <PrimaryContact telephone={value} />
}
```
also, more than likely, you will have to add a `Filter` property. Next time, please refer to the docs since all this is already written there, or to stackoverflow. Or file a clear full bug report
