### ISSUE TITLE
Performance very slow in prepareRow when row has 5000 cells

### ISSUE THREAD

**Issue by Jeffy2012** [TanStack/react-table#2961]
![image](https://user-images.githubusercontent.com/2225478/103496407-12e5ee00-4e79-11eb-9628-3905dda508e8.png)

**Comment by datner** [comment]
prepareRow will only skip rows that are not shown because they are paginated or for filtered or something. But all rendered rows are prepared in their entirety. Meaning that yes, you prepare 5000 cells per-row, I think that the issue is having 5000 columns in the first place.

Could you explain your usecase?
