### ISSUE TITLE
useSortBy API docs say "... see Sorting" as if there should be a link to other documentation, but there is no link

### ISSUE THREAD

**Issue by gimbo** [TanStack/react-table#3692]
**Describe the bug (required)**

This is a documentation bug report.

In [the API docs for `useSortBy`](https://react-table.tanstack.com/docs/api/useSortBy), we have the following text in two places:

> For more information on sort types, see Sorting

To me this looks like the word "Sorting" should be (or once was) a link to some other page, but it is not (neither in the rendered HTML nor in [the raw MD](https://raw.githubusercontent.com/TanStack/react-table/alpha/docs/api/useSortBy.md); this is doubly disappointing to the reader: they don't get the information they want, but they get a tantalising glimpse that maybe it exists somewhere.

I'm personally struggling to find more information on sort types anywhere in the documentation.

**Expected behavior (Recommended)**

I'd expect either for there to be a working link to a page with the "more information", or for the "more information" to be on the `useSortBy` page itself, or for those sentences to not be there.

**Comment by baruchiro** [comment]
I also struggling with it, since I can't find a building function that follows the sort method of the table, and I can't understand how the sort works.

As far as I can see, this is the sort: `A > A1 > A2 > A10 > 1`.

Other sort methods in JS ([`String.prototype.localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) and [`Intl.Collator()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator)) set the **number** before the **letter**.

**Comment by gimbo** [comment]
Looks to me like this is still an issue under v8, as things stand...

[Here's `useSortBy.md`](https://github.com/TanStack/react-table/blob/94b6bbe113cf3355dff753db962179ab07c78808/docs/api/useSortBy.md) as it stands today on the `alpha` branch, and it's got the same issue.

Can someone reopen this issue please?

**Comment by tannerlinsley** [comment]
None of the documentation has been updated for v8 yet. I don't plan on writing any of the docs until I release beta, so what you're seeing is just the leftover API from v7 as a placeholder. The exported TypeScript types are the biggest source of truth right now if you're using v8 alpha.

I'm not going to reopen this issue simply because it's already being tracked on our todo list in the Readme. The docs will be very thorough (much better than in v7), just like they are for React Query.

If you want to peek into how sorting works in v8 (which is still very similar to v7), you can peruse the [source here](https://github.com/TanStack/react-table/blob/alpha/packages/table-core/src/sortTypes.ts), and the [types here](https://github.com/TanStack/react-table/blob/alpha/packages/table-core/src/features/Sorting.ts#L36-L56).
