### ISSUE TITLE
8.0.0-alpha.63: bug collection

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/react-table#3884]
### Describe the bug

Things that worked for me in v58 and now don't in v63:
- filter example does not filter (https://codesandbox.io/s/wonderful-voice-ofk39q?file=/src/main.tsx)
- cannot launch examples in Codesandbox anymore (due to changed tsconfig)
- `initialState` seems to be ignored in `useTableInstance` 

Other:
- `column.getPreFilteredUniqueValues().size` works for all columns except the currently filtered ones, is that intended? (I just realized this existed in v7 already: https://codesandbox.io/s/modern-leftpad-j2jue4?file=/src/App.js)

### Your minimal, reproducible example

 https://codesandbox.io/s/modern-leftpad-j2jue4?file=/src/App.js

### Steps to reproduce

x

### Expected behavior

x

### Platform

x

### react-table version

8.0.0-alpha.63

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
- The filtering example is fixed. I accidentally set the `globalFilterFn` to `test` 😂 
- CodeSandbox examples work again, good catch!
- I just released a new `initialState` composition flow. I hope it fixes your issue 😄 

At the moment, `column.getPreFilteredUniqueValues()` returns the unique values *after any previous filters* (using the order of `state.columnFilters` but *before that column's filtering has been applied*. So essentially, the first filter applied in a sequence will always show unique values for the entire set. I realize this isn't *true* faceted filtering and I have immediate plans to fix this as soon as I can implement it in a performant way.

My plan: True faceted options are those that apply all other filters but their own all the time. So theoretically:

- Apply each filter to all columns all the time, flagging each column with a pass/fail per filter. This might have performance implications that aren't present today since our rows array to filter potentially decreases in size with each serial filter application.
- Find the faceted results of each column by applying the passing flags for all other filters excluding its own. It's likely this would need to be opt-in as it is today somehow so you only pay for the facets you use.
- Derive a final filtered row model using the intersection of all passing filter flags.

There is probably a way to have the best of both worlds where we can detect if filters can be applied serially for the best performance vs faceting. I think this means that columns will need to define if they should facet their filters ahead of time or not.
